### ISSUE TITLE
Internationalization and optional configs

### ISSUE THREAD

**Issue by BenevidesLecontes** [antoantonyk/password-strength-meter#1]
Hi, thanks for your great lib. I did some refactoring and upgraded to latest angular. I switched from `zxcvbn` to `@contentpass/zxcvbn`, to add the possibility for internationalization and optional config. If you're interested to those changes I can make a PR for you. Let me know anything.

**Comment by d4e-ch** [comment]
Hi !
I'm very interested, since I'd like to get rid of the BIG dictionnary coming from zxcvbn.
Thanks !

**Comment by antoantonyk** [comment]
@BenevidesLecontes Sure.

**Comment by BenevidesLecontes** [comment]
I'll  do soon as I can

**Comment by antoantonyk** [comment]
@NicolasRoehm Thanks for the PR. Since lots of changes happened, I am not able to merge your changes. 

@BenevidesLecontes Please check the new implementation and if still you are facing issues, feel free to reopen this thread.
