### ISSUE TITLE
How to customize background?

### ISSUE THREAD

**Issue by julioaze** [antoantonyk/password-strength-meter#12]
i need to change the background color `#DDD` to `#FFF` but I can't access the .strength-meter class that contains the background color.

**Comment by NLueg** [comment]
I struggle with that problem too.

**Comment by antoantonyk** [comment]
try overriding the style from parent component as follows,

`:host ::ng-deep password-strength-meter {
  .strength-meter {
    background: red;
  }
}
`

**Comment by NickeManarin** [comment]
Hi, `::ng-deep` is deprecated and disabling encapsulation is messful, it would be nice to have those inputs exposed, accepting custom classes.
