### ISSUE TITLE
Password warning message sentence, punctuation.

### ISSUE THREAD

**Issue by gregduffield** [antoantonyk/password-strength-meter#13]
Can you please update the warning message so that there is correct punctuation and spacing, as it does not look very good when we are telling someone that their password is not good enough.

Ideally we should be able to customise these, but in the meantime please can you fix the below

> This is a top-10 common **passwordAdd** another word or two. Uncommon words are better.

**Comment by antoantonyk** [comment]
good point. will work on this. Thanks

**Comment by Joohansson** [comment]
If anyone finds this before it's fixed. This does the trick if placed in the root style.

`.password-feedback, password-suggetion {
    display: block !important;
}`
