### ISSUE TITLE
Remove hard dependency to zxcvbn modules 

### ISSUE THREAD

**Issue by HosseinSalmanian** [antoantonyk/password-strength-meter#223]
Hi
As we provide our own implementation for IPasswordStrengthMeterService, there is no need to default PasswordStrengthMeterService.
but because imported PasswordStrengthMeterService is the default provided class in PasswordStrengthMeterModule forRoot method, there is a hard dependency on zxcvbnEnPackage.
it makes the final app bundle about 1MB larger.
I think it would be better to remove the default provider for IPasswordStrengthMeterService and let it be specified in the consumer app module.  it will remove the hard dependency on "zxcvbn" Module and the final bundle will be much smaller.
thanks in regards.

**Comment by ladyginan** [comment]
Hi!
I also use my implementation, and I need help finding a way to use the default implementation combined with mine. Is that possible? It seems to be not, but it would be nice to have the option to add only a few additional conditions there for only some of the strength levels.
