### ISSUE TITLE
Update peer dependencies to Angular 10

### ISSUE THREAD

**Issue by PooSham** [antoantonyk/password-strength-meter#23]
Angular 10 has been out for a while now, could you please update the peer dependencies? I get the following message.

> npm WARN angular-password-strength-meter@2.0.0 requires a peer of @angular/common@~9.1.3 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-password-strength-meter@2.0.0 requires a peer of @angular/core@~9.1.3 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-password-strength-meter@2.0.0 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.

tslib is now at version 2+, so you should probably update that too

Thank you!

**Comment by patrickrioux** [comment]
Yeah, noticed that too. 

Looks like the component is still working though, just ignoring the warning but please fix to work with 10.1.4.
