### ISSUE TITLE
Evaluate alternative npm packages to zxcvbn?

### ISSUE THREAD

**Issue by PooSham** [antoantonyk/password-strength-meter#24]
The npm dependency "zxcvbn" was last published 4 years ago. It's written as CommonJS and AMD modules using coffeescript, and it doesn't seem to be maintained anymore.

An issue with CommonJS and AMD is that it's harder for transpilers to optimize the code. Now that we have native modules in javascript, we should use it. For example, in my Angular 10 project, I get the following message when I build it:

> WARNING in C:\Projects\OceanCloud\ClientWebService\FrontEnd\node_modules\angular-password-strength-meter\__ivy_ngcc__\fesm2015\angular-password-strength-meter.js depends on 'zxcvbn'. CommonJS or AMD dependencies can cause optimization bailouts.

See the following issue: [ dropbox/zxcvbn: Still maintained? #290](https://github.com/dropbox/zxcvbn/issues/290)

Github user hrueger has created his own fork of zxcvbn using plain ES2015 modules. You can find the [source code here ](https://github.com/hrueger/zxcvbn) and the [npm package here](https://www.npmjs.com/package/zxcvbn3).

**Comment by antoantonyk** [comment]
Yeah, will do that on the next release.

**Comment by antoantonyk** [comment]
For now, am using zxcvbn3 lib. If any issues raises due to this will revert back. @PooSham Thank you for sharing the details.

**Comment by mrienstra** [comment]
[npmjs.com/zxcvbn3](https://www.npmjs.com/package/zxcvbn3) doesn't appear to be actively maintained, it currently points to [github.com/hrueger/zxcvbn](https://github.com/hrueger/zxcvbn) which is "1 commit ahead, 59 commits behind zxcvbn-ts:master". That single commit ([diff](https://github.com/zxcvbn-ts/zxcvbn/compare/master...hrueger:master)) is adding this line to `README.md`:
>⚠ Moved to https://github.com/MrWook/zxcvbn

[github.com/MrWook/zxcvbn](https://github.com/MrWook/zxcvbn) in turn, is "1 commit ahead of dropbox:master", and that single commit ([diff](https://github.com/dropbox/zxcvbn/compare/master...MrWook:master)) is modifying `README.md` to link to [github.com/zxcvbn-ts/zxcvbn](https://github.com/zxcvbn-ts/zxcvbn).

... Which looks considerably more "alive" ([here's snyk.io's take](https://snyk.io/advisor/npm-package/@zxcvbn-ts/core?utm_medium=referral&utm_source=skypack&utm_campaign=snyk-widget)).

NPM: https://www.npmjs.com/package/@zxcvbn-ts/core
Migration guide: https://zxcvbn-ts.github.io/zxcvbn/guide/migration/
Repo: https://github.com/zxcvbn-ts/zxcvbn
