### ISSUE TITLE
Uneven strength bar widths

### ISSUE THREAD

**Issue by alastair-todd** [antoantonyk/password-strength-meter#26]
I had to add this to my container

```
::ng-deep .strength-meter {
    &::before,
    &::after {
      box-sizing: border-box;
    }
  }
```

**Comment by antoantonyk** [comment]
is it happened after using the above style?

**Comment by alastair-todd** [comment]
No it happened, then to fix it I added that style, so was suggesting to add it to the component.

**Comment by antoantonyk** [comment]
https://antoantonyk.github.io/password-strength-meter/

I just checked on the demo page and it seems like there is no issue.

**Comment by rubiesonthesky** [comment]
In demo the box-sizing: border-box is coming from some global styling:

```
*, ::after, ::before {
    box-sizing: border-box;
}
```

If user does not have that in their project, after and before won't have border-box properties. If you remove that styling from demo page, the bars are uneven.

**Comment by antoantonyk** [comment]
@rubiesonthesky oh got it, thanks for pointing out. will release a fix based on this asap.
