### ISSUE TITLE
Must import into AppModule - error when importing into other modules.

### ISSUE THREAD

**Issue by lmordell** [antoantonyk/password-strength-meter#278]
I have a lazily loaded route, 'register', that is the only one to use the password-strength-meter. As such, I added the `PasswordStrengthMeterModule` to the RegisterModule's list of imports. When I navigate to the register route however, I get the following error:

`core.mjs:7640 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[IPasswordStrengthMeterService -> IPasswordStrengthMeterService -> IPasswordStrengthMeterService]: 
  NullInjectorError: No provider for IPasswordStrengthMeterService!
NullInjectorError: R3InjectorError(AppModule)[IPasswordStrengthMeterService -> IPasswordStrengthMeterService -> IPasswordStrengthMeterService]: 
  NullInjectorError: No provider for IPasswordStrengthMeterService!`

I'm only able to fix it by importing the `PasswordStrengthMeterModule` in both the `AppModule` and the `RegisterModule`. I should only need to register it in the `RegisterModule`.

**Comment by antoantonyk** [comment]
did you import the module to `RegisterModule` with forRoot?

PasswordStrengthMeterModule.forRoot()

**Comment by antoantonyk** [comment]
https://stackblitz.com/edit/angular-qxj35e-luomnc?file=src/app/orders/orders-routing.module.ts

Here is the sample

**Comment by lmordell** [comment]
>did you import the module to RegisterModule with forRoot?

I did, but it must have been an environment issue on my end because it's working now. Apologies for the false alarm.
