### ISSUE TITLE
How to get rid of "not found" printing in console

### ISSUE THREAD

**Issue by Jason4Ever** [antoantonyk/password-strength-meter#33]
Hi,

I was able to implement the plugin successfully in my angular app, and I have disabled the feedbacks, However I still see the browser keeps printing out "not found" .. My initial check is this happens  while trying to translate the feedbacks (although of I disabled it).

Any thoughts how can I stop this ?

**Comment by antoantonyk** [comment]
I am not able to reproduce this issue. Closing this for now. If you are still facing this issue, Feel free to reopen this with a screenshot
