### ISSUE TITLE
Use different zxcvbn fork

### ISSUE THREAD

**Issue by mrienstra** [antoantonyk/password-strength-meter#36]
Continuation of #24:

[npmjs.com/zxcvbn3](https://www.npmjs.com/package/zxcvbn3) doesn't appear to be actively maintained, it currently points to [github.com/hrueger/zxcvbn](https://github.com/hrueger/zxcvbn) which is "1 commit ahead, 59 commits behind zxcvbn-ts:master". That single commit ([diff](https://github.com/zxcvbn-ts/zxcvbn/compare/master...hrueger:master)) is adding this line to `README.md`:
>⚠ Moved to https://github.com/MrWook/zxcvbn

[github.com/MrWook/zxcvbn](https://github.com/MrWook/zxcvbn) in turn, is "1 commit ahead of dropbox:master", and that single commit ([diff](https://github.com/dropbox/zxcvbn/compare/master...MrWook:master)) is modifying `README.md` to link to [github.com/zxcvbn-ts/zxcvbn](https://github.com/zxcvbn-ts/zxcvbn).

... Which looks considerably more "alive" ([here's snyk.io's take](https://snyk.io/advisor/npm-package/@zxcvbn-ts/core?utm_medium=referral&utm_source=skypack&utm_campaign=snyk-widget)).

NPM: https://www.npmjs.com/package/@zxcvbn-ts/core
Migration guide: https://zxcvbn-ts.github.io/zxcvbn/guide/migration/
Repo: https://github.com/zxcvbn-ts/zxcvbn

PS: The creators of those first two forks (hrueger, MrWook) have also [contributed to `zxcvbn-ts/zxcvbn`](https://github.com/zxcvbn-ts/zxcvbn/graphs/contributors), as per [this comment](https://github.com/dropbox/zxcvbn/issues/290#issuecomment-754791316).
PPS: Opened PRs to clarify the situation: [1](https://github.com/MrWook/zxcvbn/pull/1), [2](https://github.com/hrueger/zxcvbn/pull/2).

**Comment by 40rn05lyv** [comment]
Totally agree, please update the README file which is misleading.

**Comment by antoantonyk** [comment]
@mrienstra I have integrated the zxcvbn-ts.
