### ISSUE TITLE
Feedback text in multiple Languages

### ISSUE THREAD

**Issue by lauhon** [antoantonyk/password-strength-meter#45]
As of now it is not possible to provide the feedback text in any language other then english.

Would be great to either have multiple languages supported ootb or to just be able to pass custom strings to the component.

Maybe these are some recources to make this possible:

https://zxcvbn-ts.github.io/zxcvbn/guide/languages/#add-a-new-language-package
https://www.npmjs.com/package/@contentpass/zxcvbn#usage (search for "feedback_messages")

**Comment by antoantonyk** [comment]
@lauhon Please check version 4.0.0
