### ISSUE TITLE
zxcbn3 : tolowercase is not a function

### ISSUE THREAD

**Issue by SalmanQureshi97** [antoantonyk/password-strength-meter#48]
Running angular password stength meter in my ionic app. Gives a uncaught promise error where it says that toLowerCase is not a function when converting the password to lowercase in zxcbn3.

**Comment by wmehanna** [comment]
Be sure to set your password to an exposed variable from your component.
ex:
Your component.ts
public myExposedPassword = 'Password example';

Your component.html
<password-strength-meter [password]="myExposedPassword"></password-strength-meter>

**Comment by antoantonyk** [comment]
Feel free to reopen the thread, if you are facing this issue again
