### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by rbanno** [antoantonyk/password-strength-meter#51]
When using the demo page for this component I tried using entering password and password123, the latter came back as a "green" password. This is a really common password, how comes the strength isn't lower?

If I do the same thing using: https://lowe.github.io/tryzxcvbn/, then this comes back with a score of 0. 

Output from above:

_> password: | password123
> guesses_log10: | 2.77525
> score: | 0 / 4
> function runtime (ms): | 0
> guess times:
> 100 / hour: | 6 hours | (throttled online attack)
> 10  / second: | 60 seconds | (unthrottled online attack)
> 10k / second: | less than a second | (offline attack, slow hash, many cores)
> 10B / second: | less than a second | (offline attack, fast hash, many cores)
> warning: | This is a very common password
> suggestions: | - Add another word or two. Uncommon words are better._

Is this something that can be configured within the component?

**Comment by rbanno** [comment]
Apologies, I tried the vue.js component and that worked as I would expect, so I am hopeful this is something that can be configured.

Please see the screen shots below, both testing with password123

**Vue.js example**
![image](https://user-images.githubusercontent.com/11596414/142442107-a0f8171b-3ab2-45ef-9ed5-0c2b77be8ed1.png)

**Angular example**
![image](https://user-images.githubusercontent.com/11596414/142442279-2b371b94-1123-4042-b3c1-1d73edc168eb.png)

**Comment by PooSham** [comment]
This package uses the npm package `zxcvbn3` to calculate the score, not dropbox's original implementation. That npm package isn't maintained anymore (and probably not this one either). I might try to maintain a fork of this project where [zxcvbn-ts](https://github.com/zxcvbn-ts/zxcvbn) is used as default (maybe with the possibility to easily inject another score calculator). zxcvbn-ts gives "password123" a score of 0, check it out here: https://zxcvbn-ts.github.io/zxcvbn/demo/

**Comment by rbanno** [comment]
Thanks – that looks like a great option

**Comment by antoantonyk** [comment]
Hi all,

I just updated the lib with [zxcvbn-ts](https://github.com/zxcvbn-ts/zxcvbn). Hope this will solve the issue.
