### ISSUE TITLE
Need to Support Angular 15

### ISSUE THREAD

**Issue by abdo-host** [antoantonyk/password-strength-meter#579]
We Need to Support Angular 15, please update it to working with Angular 15

**Comment by abdo-host** [comment]
Any updates?

**Comment by huajian123** [comment]
I need this library

**Comment by antoantonydh** [comment]
Hello all,

I will work on the update this week. Sorry for the delays

**Comment by allendewilzin** [comment]
What is the ETA on this?

**Comment by abdo-host** [comment]
@antoantonydh any updates?

**Comment by huajian123** [comment]
yes,I'm waiting for official support. I'll copy the source code to my angular15 project now, and make a slight modification to run it normally, but it looks bloated
https://github.com/huajian123/ng-ant-admin/tree/master/src/app/shared/biz-components/password-strength-meter
