### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by DouglasLapsley** [antoantonyk/password-strength-meter#61]
Could you please update to work with Angular 13.  Thanks!

**Comment by Tohnmeister** [comment]
I'm not the library author, but what exactly do you mean with Angular 13 support? I'm still on version 3.0.1 and it works well with Angular 13. It has a peer dependency on Angular version 10 or higher.

**Comment by DouglasLapsley** [comment]
If I remember rightly it was just complaining about dependency versions.  If it works for you then not to worry.  It was stopping me from being able to use it at the time though.
