### ISSUE TITLE
Does this package support providing a UserInput array to zxcvbn-ts?

### ISSUE THREAD

**Issue by tobias-graf-p** [antoantonyk/password-strength-meter#632]
The `zxcvbn-ts` lib allows to provide a `UserInput` array. See here: https://zxcvbn-ts.github.io/zxcvbn/guide/user-input/

Is this supported by this package?

**Comment by antoantonyk** [comment]
Hey @tobias-graf-p ,

did you try with the PSM_CONFIG provider to give these options?

```
@NgModule({
    ...
    imports: [
        ....
        PasswordStrengthMeterModule.forRoot()
    ],
    providers: [
      {
        provide: PSM_CONFIG,
        useValue: {
          translations: zxcvbnEnPackage.translations,
          graphs: zxcvbnCommonPackage.adjacencyGraphs,
          dictionary: {
            ...zxcvbnCommonPackage.dictionary,
            ...zxcvbnEnPackage.dictionary,
             userInputs: ['someEmail@email.de', 'someUsername'],
          },
        }
      }
    ],
    ....
})
export class AppModule { }
```

**Comment by tobias-graf-p** [comment]
@antoantonyk Thanks for your reply. Your suggestion would use the same values for all users, wouldn't it?

Anyway, meanwhile we used zxcvbn-ts directly and implemented our own password strength meter. So it is not relevant for us anymore. If you like, you can close this issue.

**Comment by antoantonyk** [comment]
@tobias-graf-p yes. you are right. We don't support per user.  Glad you have found another solution
